name: Domains Recon
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Install dnsx
        run: go install -v github.com/projectdiscovery/dnsx/cmd/dnsx@latest
      
      - name: Install naabu
        run: |
          sudo apt-get update
          sudo apt-get install -y libpcap-dev
          go install -v github.com/projectdiscovery/naabu/v2/cmd/naabu@latest
      
      - name: Install httpx
        run: go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest
      
      - name: Add Go bin to PATH
        run: echo "$HOME/go/bin" >> $GITHUB_PATH
      
      - name: Test endpoint
        run: |
          curl http://52.205.193.100:8000/subdomains-dnsx.txt -o subdomains-dnsx.txt
          cat subdomains-dnsx.txt | dnsx | naabu -top-ports 100 | httpx -title -sc -cl -tech-detect
